- .github/workflows/make.yml
- Makefile
- build.gradle
- src/com/xilinx/fpga24_routing_contest/CheckPhysNetlist.java
1. Since GitHub Actions has no access to Vivado, currently the `report_route_status` functionality always returns a mock PASS status.
2. Due to GitHub Actions memory limitations (7GB RAM), `rwroute` can only tackle the two smallest benchmarks.
3. Since `nxroute-poc` only operates on one clock region of the device, it can partially route all five benchmarks.
4. The resulting log/physical netlist/DCPs of all 2 (`rwroute`) + 5 (`nxroute`) runs are uploaded as artifacts for 90 days.
> GitHub Actions to run example routers

- Makefile
Java's initial heap size to be the same as maximum heap size (just shy of 32GB) to minimize reallocations.
> Fix typo Xmx -> Xms

- .github/workflows/make.yml
- Makefile
- src/com/xilinx/fpga24_routing_contest/CheckPhysNetlist.java
In this contest, Vivado's `report_route_status` is used to check the validity of the routed result. In some cases, it may desirable to acquire this result from a remote server running Vivado. This capability is enabled by this PR when the following two environment variables are set:
* `REPORT_ROUTE_STATUS_URL`
* `REPORT_ROUTE_STATUS_AUTH`
Without these two variables set, the local install of Vivado will be used, as is the case before this PR.
Two ways of using this capability:
1. Running outside of GitHub Actions:
* `make REPORT_ROUTE_STATUS_URL=<url> REPORT_ROUTE_STATUS_AUTH=<user:pass> ...`
2. Running inside GitHub Actions:
* Use the [GitHub secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) facility to set …
> Add ability to execute report_route_status on remote server

- docs/start.md
Note added to website on RWRoute's default JVM heap size of 32GB, and how that can be reduced:
```
make JVM_HEAP="-Xms14g -Xmx14g"
```
Also a note on how the `VERBOSE` flag can also be set to echo output to the screen as well as logging to file:
```
make VERBOSE=1
```
> [Doc] Note on RWRoute memory req & VERBOSE flag

- src/com/xilinx/fpga24_routing_contest/DcpToFPGAIF.java
In #10, alternate sources were set up before writing out the FPGAIF Physical Netlist.
Unfortunately, I omitted to add the alternate source `SitePinInst` to the net and thus it was not written out into the Physical Netlist. Fixed in this PR.
> Fix DcpToFPGAIF to add alternate SitePinInst to net

- .github/workflows/make.yml
- requirements.txt
* Unpin specific versions from `requirements.txt`.
* Temporarily build `pycapnp` from source until 3.12 wheel is available.
> [Actions] Update to Java 21, Python 3.12; cleanup requirements

- .github/workflows/make.yml
- Makefile
- docs/score.md
- wirelength_analyzer/xcvup_device_data.py
Also be more precise with long wire regex.
Remove unnecessary `CHECK_PHYS_NETLIST_MOCK_PASS` capability.
> Fix wirelength_analyzer regex warnings

- wirelength_analyzer/wa.py
Raise a `ValueError` unless the PIP tile's root name (i.e. the prefix before `_X*Y*`) belongs to:
* `INT*`
* `CLEL_R`
* `CLEM`
* `CLEM_R`
* `BRAM`
* `DSP`
* `XIPHY_BYTE_L` (needed by `ispd16_example2` since it is in-context)
* `HPIO_L` (needed by `ispd16_example2` since it is in-context)
* `CMT_L` (needed by `ispd16_example2` since it is in-context)
> wirelength_analyzer to check PIP tile before assigning zero WL

- .github/workflows/make.yml
- .github/workflows/scoring_criteria.yml
Unfortunately, it looks like even the latest Gradle (8.4 currently) does [not support](https://docs.gradle.org/current/userguide/compatibility.html) running itself (but it does building other applications) using Java 21.
Downgrading to Java 17 to keep things simple.
> [Actions] Downgrade to Java 17

- docs/score.md
- wirelength_analyzer/wa.py
- wirelength_analyzer/xcvup_device_data.py
Add connectivity rules for cells of type:
- `MMCE4_ADV`
- `GTYE4_CHANNEL`
- `GTYE4_COMMON`
- `PCIE40E4`
- `URAM288`
- `STARTUPE3`
- `ICAPE3`
Also add a new PIP wirelength entry, some small refactors, and documentation updates to reflect above changes.
> [WirelengthAnalyzer] Add new connectivity rules

- Makefile
- src/com/xilinx/fpga24_routing_contest/PartialRouterPhysNetlist.java
* Update RapidWright to latest [upstream](https://github.com/Xilinx/RapidWright), which notably pulls in:
* https://github.com/Xilinx/RapidWright/pull/884 which should improve routing performance for congested designs
* https://github.com/Xilinx/RapidWright/pull/885 to aid the point below
* `PartialRouterPhysNetlist` has been modified to demonstrate how key router parameters can be changed
> Update RapidWright submodule

- Makefile
- requirements.txt
Since [pycapnp-2.0.0b2](https://pypi.org/project/pycapnp/2.0.0b2/#files) adds pre-compiled wheels for Python 3.12.
> Update requirements.txt to use pre-release pycapnp

- .github/workflows/test-container.yml
- .gitignore
- Makefile
- alpha_submission/README.md
- alpha_submission/nxroute-poc_container.def
- alpha_submission/opencl_example/opencl_example_container.def
- alpha_submission/rwroute_container.def
- docs/alpha_submission.md
- docs/index.md
Adds:
- Infrastructure to support the alpha submission
- GitHub Action run for Apptainer flow
- Documentation describing the alpha submission process
> Alpha submission

- .github/workflows/make.yml
- Makefile
- docs/score.md
- wirelength_analyzer/xcvup_device_data.py
* Fixed `corundum_25g` benchmark (that does not have site pins for `inout` ports)
* Add `INBUF` and `OBUFT` as cells that `wirelength_analyzer` recognizes
* Fix GHA workflow to check for no sources/stubs
> Fix stubs in corundum_25g

- wirelength_analyzer/wa.py
An example of this occurring is the case when the LUT drives a hierarchical (out of context) port, so it becomes the terminus.
> Fix wirelength_analyzer when terminating at a comb cell (e.g. LUT)

- networkx-proof-of-concept-router/nxroute-poc.py
It turns out that there are some connections (e.g. those driven by an IBUF) require the use of a routethru PIP in order to be routeable. Enable such PIPs, but continue to disable CLE routethrus (representing LUT routethrus, which require a lot more work to determine if it's legal to use) and RCLK routethrus (representing BUFCE routethrus which allows access onto the global routing network).
This scenario does not show up GitHub Actions since NXRoute is restricted to a small window of the device, and so far we don't have the above occurrence in our chosen window.
> [NXRoute] Allow routethru PIPs for non-CLE/RCLK tiles

- docs/score.md
- wirelength_analyzer/xcvup_device_data.py
Primitive used for differential inputs, seen in the `corescore` and `corundum` benchmarks.
> [wirelength_analyzer] Add support for DIFFINBUF

- .github/workflows/net_printer.yml
- Makefile
Notably, pulling in:
* https://github.com/Xilinx/RapidWright/pull/928 and
https://github.com/Xilinx/RapidWright/pull/929
Fixes various FPGAIF issues with stubs incorrectly appearing on static nets
* https://github.com/Xilinx/RapidWright/pull/927
Fixes an issue with FPGAIF nets associated with differential IOs
* https://github.com/Xilinx/RapidWright/pull/924
Fixes an issue when RWRoute's LUT pin swapping feature is enabled
* https://github.com/Xilinx/RapidWright/pull/923
Fixes an issue where intra-site static routing was being dropped in FPGAIF
* https://github.com/Xilinx/RapidWright/pull/921
Small bugfix in RWRoute which should slightly improve performance
The fixes in https://github.com/Xilinx/RapidWright/pull/928 & https://github.com/Xilinx/RapidWright/pull/929, …
> [RapidWright] Pull in PhysNetlistWriter + RWRoute fixes

- .github/workflows/net_printer.yml
- Makefile
- networkx-proof-of-concept-router/nxroute-poc.py
From the discussion here: https://github.com/Xilinx/fpga24_routing_contest/discussions/54#discussioncomment-7921770 it may not have been clear how the resources used by pre-routed nets -- clocks, ground, vcc -- can be identified such that they cannot be used by a contestant router.
This is now demonstrated in NXRoute, where resources used by pre-routed nets are removed from the routing graph.
In order to achieve this, some more state needed to be carried about the graph, which may increase memory consumption. On the other hand, I think I identified an optimization which prevents new strings from `pycapnp` being created on every lookup, so there may be a saving too.
On `boom_med_pb`, self-reporting using the added line shows that NXRoute now takes ~45GB for the whole device so I've upped …
> [NXRoute] Eliminate route conflicts with pre-routed nets

- docs/score.md
- wirelength_analyzer/xcvup_device_data.py
Since the `xcvu3p` is a single SLR device, no SLR crossings exist. However, one can use Laguna tiles to perform a "U-turn" from an `INT` tile (leaving on the lime green node) back into the `INT tile` (re-entering on the red node, via three pink PIPs):
This PR adds support for these three PIPs to the `WirelengthAnalyzer`.
> [WirelengthAnalyzer] Support U-turns in Laguna tiles

- .github/workflows/make.yml
- Makefile
- src/com/xilinx/fpga24_routing_contest/CheckPhysNetlist.java
As part of the contest rules, routers are only allowed to modify the inter-site routing (PIPs) of the input Physical Netlist. Verify this is the case by leveraging RapidWright's `DesignComparator` feature: https://github.com/Xilinx/RapidWright/pull/931.
> [CheckPhysNetlist] Verify placement & static/clock routing unchanged

- README.md
- src/com/xilinx/fpga24_routing_contest/DiffPhysNetlist.java
[Contest rules](https://xilinx.github.io/fpga24_routing_contest/details.html#framework) stipulate that the intra-site routing and placement of the input physical netlist cannot be modified (only inter-site routing/PIPs may be inserted). This is now verified by `CheckPhysNetlist` as of https://github.com/Xilinx/fpga24_routing_contest/pull/64.
This new `DiffPhysNetlist` utility provides a more detailed report for any diffs found, and can be used like so:
```
./gradlew -Dmain=com.xilinx.fpga24_routing_contest.DiffPhysNetlist :run --args="boom_soc_routed.phys boom_soc_unrouted.phys"
```
> Add DiffPhysNetlist utility

- .github/workflows/make.yml
- .github/workflows/net_printer.yml
- Makefile
- docs/benchmarks.md
- docs/contact.md
Make two hidden benchmarks `logicnets_jscl` and `finn_radioml` used for alpha submission evaluation public.
Also updates RapidWright to `2023.2.1` (with a number of improvements relevant and irrelevant to RWRoute) plus two fixes:
- https://github.com/Xilinx/RapidWright/pull/938
- https://github.com/Xilinx/RapidWright/pull/939
that were necessary to ensure the `finn_radioml` result is correct with RWRoute's `--lutPinSwapping` option.
> Add logicnets_jscl and finn_radioml, with fixes

- .github/workflows/make.yml
- src/com/xilinx/fpga24_routing_contest/PartialRouterPhysNetlist.java
Pulls in https://github.com/Xilinx/RapidWright/pull/932 which added a `--lutRoutethru` option to RWRoute that allows it to consider using unused LUTs as additional routing resources.
As the data in https://github.com/Xilinx/RapidWright/pull/932#issuecomment-1881532199 shows, enabling this option does not unanimously improve the runtime across all benchmarks, and so it is disabled (commented out) by default.
> [RWRoute] Add --lutRoutethru option (disabled by default)

- .github/workflows/make.yml
- Makefile
- build.gradle
- compute-score.py
Measure user-CPU time of router just for informational purposes only.
Apparently, Gradle almost always launches itself as a daemon and it was discovered that `/usr/bin/time` cannot capture the user-CPU time of routers spawned from that daemon. Thus, the RWRoute target had to be reworked to invoke `java` directly.
> [Makefile] Track user-cpu time (not used for scoring)

- Makefile
As per contest rules, disable network access when running routers.
For this to work, an extra `setup-container` recipe was needed which first fulfills all dependencies (particularly contest infrastructure, which pulls in Java packages from Gradle and Python packages from pip).
> Disable network access for {run-,test-} container recipes

- Makefile
So that it can be propagated through to the `setup-benchmarks` recipe which only downloads necessary benchmarks.
> Propagate BENCHMARKS in setup-container recipe

- .github/workflows/make.yml
- Makefile
- alpha_submission/rwroute_container.def
- docs/results.md
- final_submission/rwroute_container.def
- src/com/xilinx/fpga24_routing_contest/CheckPhysNetlist.java
- Revisit GitHub Actions workflow since GitHub hosted runners now have 4 cores and 16GB of RAM.
- Now all of the original benchmarks can be run in GHA!
- Fix Apptainer test too.
- Add links to open-source code from the 3 teams who elected to release
- Also integrated into this repository under a branch
- Add links to publications made by our winners
> Update/fix Actions; add open-source links/publications

- .github/workflows/make.yml
- Makefile
- alpha_submission/rwroute_container.def
- docs/benchmarks.md
- docs/results.md
- final_submission/rwroute_container.def
- src/com/xilinx/fpga24_routing_contest/CheckPhysNetlist.java
> Merge master into 2nd-cufr branch
